
<?php
    $this->setPageTitle('user.management');
    $formatting = $this->getHelper('DataFormatting');
?>

<?php
    if($this->isPublisher){
?>
    <form id="ajaxForm" action="objectType/save" method="post" onsubmit="Form.submit('ajaxForm'); return false;">
        <input type="hidden" name="id" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getId()):'')?>" />
        <div class="fixed_head">
            <span class="tableTitle"><?php echo $this->translate('publisher'). ' // ' . ($this->item ? $this->translate('edit'): $this->translate('add')); ?></span>        
            <table class="editTable">                    
                <tbody>                    
                    <tr>
                        <td class="middle left w180"><label for="name"><?php echo $this->translate('name')?> *</label></td>
                        <td class="middle left"><input type="text" name="name" id="name" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getName()):'')?>"/></td>                    
                    </tr>    
                    <tr>
                        <td class="middle left"></td>
                        <td class="middle left"><input type="button" onclick="Form.submit('ajaxForm')" value="save"/></td>
                    </tr>                     
                </tbody>
                <tfoot><tr><td class="h p5_0"></td></tr></tfoot>
            </table>
        </div> 
    </form>
    <?php }else{ ?>
        <div>
            <?php echo $this->translate('this.action.only.for.publishers');?>
        </div>
    <?php } ?>