<?php 
    $this->setPageTitle('objectype'); 
    $formatting = $this->getHelper('DataFormatting');
?>
<script>
$(function(){
    Grid.init('club/list');
	Menu.acitvate('objecttype');
});

</script>
<div id="deleteFormDiv">

</div>
<?php if($this->isAdmin){ ?>
    <a class="button fl mt5 ml20 mr20" href="objecttype/add" ><?php echo $this->translate('add') ?></a><br><br><br><br>
<?php } ?>
<?php echo $this->action('list', 'objecttype');?></td>
    


