<script>
	$(function(){
		$('.objectsTypesLink>a').click(function(){
			$('#objectTypeId').attr('value',$(this).attr('data-id'));
			Filter.submit('ajaxForm');
		});
	});
</script>
<div>
    <form action="objects/list" name="ajaxForm" id="ajaxForm">
        <div class="fl mr5">
            <select name="objectTypeId" id="objectTypeId">
                <option value="">--Select--</option>
                <?php
                    foreach($this->types as $item){
                ?>
                    <option value="<?php echo $item->getId() ?>" <?php echo ($this->objectTypeId==$item->getId())?'selected="selected"':''; ?>><?php echo $this->translate($item->getName()); ?></option>
                <?php
                    }
                ?>
            </select>
        </div>
		<div class="fl mr5">
            <select name="publisherId" id="publisherId">
                <option value="">--Select--</option>
                <?php
                    foreach($this->publishers as $item){
                ?>
                    <option value="<?php echo $item->getId() ?>" <?php echo ($this->publisherId==$item->getId())?'selected="selected"':''; ?>><?php echo $this->translate($item->getName()); ?></option>
                <?php
                    }
                ?>
            </select>
        </div>
		<div class="fl mr5">
            <select name="shopListId" id="shopListId">
                <option value="">--Select--</option>
                <?php
                    foreach($this->shopList as $item){
                ?>
                    <option value="<?php echo $item->getId() ?>" <?php echo ($this->shopListId==$item->getId())?'selected="selected"':''; ?>><?php echo $this->translate($item->getName()); ?></option>
                <?php
                    }
                ?>
            </select>
        </div>
		<div class="fl mr5 pt8">
			cost from
		</div>
		<div class="fl mr5">
			<input type="text" class="w50 textField mt0" placeholder="min" name="costMin"/>
		</div>
		<div class="fl mr5 pt8">
			to
		</div>
		<div class="fl mr5">
			<input type="text" class="w50 textField mt0" placeholder="max" name="costMax"/>
		</div>
        <div class="fl mr5">
            <a class="button w50"  onclick="Filter.submit('ajaxForm');return false;"><?php echo $this->translate('filter'); ?></a>
        </div>
        <?php if($this->isPublisher){ ?>
        <div class="fl mr5">
            <a href="objects/add" class="button w50"><?php echo $this->translate('add'); ?></a>
           
        </div>
         <?php } ?>
    </form>
    <br/>
   
    <br/>
    <table class="mt20">
    	<tbody>
    		<tr class="head">
                <td>
                </td>
            </tr>
    		<tr class='panel'>
    			<td>
                    <script>
                        $(function(){
                            LoveListObject.init();
                        });
                    </script>
                    <div>
                        <form id="addForm" name="addForm" action="<?php echo ($this->isUser)?'lovelist/save':'objects/delete' ?>">
                        </form>
                        <input type="button" onclick="Form.submit('addForm')" value="submit" id="addToLoveList" style="display:none;">
                    </div>
                    <div id="objectList" style="width:100%;">
                        <?php
                            foreach($this->objects as $item){
                        ?>	
                            <div data-id="object_<?php echo $item->getId();?>" class="objectContentDiv fl">
                                <div class="objectHeader">
                                    <div>
                                        <?php echo ($item->getName())?$item->getName():'no description';?>
                                    </div>
                                </div>
                                <div class="objectDiv">
                                    <img src="<?php echo $item->getPath();?>">
                                </div>
                                <div class="favourDiv">
                                    <a data-img="oneStar.png" data-evaluation="1"></a>
                                    <a data-img="twoStars.png" data-evaluation="2"></a>
                                    <a data-img="threeStars.png" data-evaluation="3"></a>
                                    <a data-img="fourStars.png" data-evaluation="4"></a>
                                    <a data-img="fiveStars.png" data-evaluation="5"></a>
                                </div>    
                                <div class="actionDiv">
                                    <div>
                                        <?php echo ($item->getCost())?$item->getCost():'0';?> <?php echo $this->getValuta($item->getValuta()); ?>
                                    </div>
                                    <a class="unSelectedLoveList" id="add_<?php echo $item->getId();?>" onclick="LoveListObject.detectOption('add_<?php echo $item->getId();?>')"></a>
                                    <a href="objects/<?php echo $item->getId();?>/overview" class="link fl overview" ></a>
                                </div>
                            </div>
                        <?php
                            }
                        ?>
                    </div>
                </td>
    		</tr>
    	</tbody>
    </table>
</div>
