<script>
	$(function(){
        LoveListObject.init();
    })
</script>
<div>
	<form id="addForm" name="addForm" action="<?php echo ($this->isUser)?'lovelist/save':'objects/delete' ?>">
	</form>
	<input type="button" onclick="Form.submit('addForm')" value="submit" id="addToLoveList" style="display:none;">
</div>
<style>
	.active>td{
        background:green !important;
    }
    .inProccess>td{
        background:orange !important;
    }
    .deactive>td{
        background:red !important;
    }
	.scroll{
		max-height:500px;
		width:500px;
		margin:5px;
		padding:5px;
		overflow:auto;
		float:left;
	}
	.scroll>table>thead>tr>td{
		color:white;
		background:rgb(152, 160, 255);
		font-size:18px;
		border:1px solid white;
		padding:5px;
		text-align:center;
	}
	.scroll>table>tbody>tr>td{
		color:white;
		background:rgb(194, 194, 194);
		font-size:15px;
		border:1px solid white;
		padding:5px;
		text-align:center;
	}
</style>
<div id="objectList" style="width:100%;">
	<?php
		if(!$this->isPublisher){
		foreach($this->items as $item){
	?>	
        <div data-id="object_<?php echo $item->getId();?>" class="objectContentDiv fl">
            <div class="objectHeader">
                <div>
                    <?php echo ($item->getName())?$item->getName():'no description';?>
                </div>
            </div>
            <div class="objectDiv">
                <img src="<?php echo $item->getPath();?>">
            </div>
            <div class="favourDiv">
                <a data-img="oneStar.png" data-evaluation="1"></a>
                <a data-img="twoStars.png" data-evaluation="2"></a>
                <a data-img="threeStars.png" data-evaluation="3"></a>
                <a data-img="fourStars.png" data-evaluation="4"></a>
                <a data-img="fiveStars.png" data-evaluation="5"></a>
            </div>    
            <div class="actionDiv">
                <div>
                    <?php echo ($item->getCost())?$item->getCost():'0';?> <?php echo $this->getValuta($item->getValuta()); ?>
                </div>
				<a class="unSelectedLoveList" id="add_<?php echo $item->getId();?>" onclick="LoveListObject.detectOption('add_<?php echo $item->getId();?>')"></a>
				<a href="" class="link fl overview" ></a>
            </div>
        </div>
	<?php
			}
		}else{
		$statusDetect = $this->getHelper('getStatus');
		
		?>
		<div class="scroll">
			<table>
				<thead>
					<tr>
						<td>
							<?php echo $this->translate('object.name'); ?>
						</td>
						<td>
							<?php echo $this->translate('views'); ?>
						</td>
						<td>
							<?php echo $this->translate('group.name'); ?>
						</td>
						<td>
							<?php echo $this->translate('activated'); ?>
						</td>
						<td>
							<?php echo $this->translate('action'); ?>
						</td>
					</tr>	
				<thead>
				<tbody>
					<?php foreach($this->items as $item){ ?>
						<tr class="<?php echo $statusDetect->getStatus($item->getActive());?>">
							<td>
								<?php echo $item->getName(); ?>
							</td>
							<td>
								<?php echo $item->getPopulation(); ?>
							</td>
							<td>
								<?php echo $item->getObjectGroupId(); ?>
							</td>
							<td>
								<?php echo $statusDetect->getStatus($item->getActive()); ?>
							</td>
							<td>
								<a href="objectsgroup<?php echo (!$item->getObjectGroupId())?'':'/'.$item->getObjectGroupId(); ?>/edit" class="ml5 mr5 mt5"><?php echo $this->translate('edit.group');?></a>
								<a href="objects/<?php echo $item->getId(); ?>/edit"  class="ml5 mr5 mt5"><?php echo $this->translate('edit');?></a>
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
		
		<div class="scroll">
			<table>
				<thead>
					<tr>
						<td>
							<?php echo $this->translate('group.name'); ?>
						</td>
						<td>
							<?php echo $this->translate('action'); ?>
						</td>
					</tr>	
				<thead>
				<tbody>
					<?php 
						if($this->objectsGroup){
						foreach($this->objectsGroup as $item){ ?>
						<tr>
							<td>
								<?php echo $item->getName(); ?>
							</td>
							<td>
								<a href="objectsgroup/<?php echo $item->getId(); ?>/edit"  class="ml5 mr5 mt5"><?php echo $this->translate('edit');?></a>
							</td>
						</tr>
					<?php }} ?>
				</tbody>
			</table>
		</div>
	<?php } ?>
</div>