<script>
	selected = '';
	$(function(){
		$('.menu').click(function(){
			$('.forFInd').hide(500);
		});
		$('.objectsTypes').click(function(){
			if(selected != 'objectsTypes'){
				selected = 'objectsTypes';
				$('.forFInd').hide(500);
				$('.objectsTypesLink').show(500);
			}
		});
	});
</script>
<div class="nav">
    <?php 
        if(!$this->isPublisher){
        ?>
        <div>
			<a href="objects"><?php echo $this->translate('objects')?></a>
		</div>
		<div>
			<a href="objecttype"><?php echo $this->translate('objecttype')?></a>
		</div>
		<div>
			<a href="publisher"><?php echo $this->translate('publisher')?></a>
		</div>
		<div>
			<a href="shoplist" class="<?php echo (!$this->isUser)?'navDivlastChildA':''; ?>"><?php echo $this->translate('shoplist')?></a>
		</div>		
    <?php } else{
        ?>
        <div>
            <a href="publisher<?php echo ($this->publisherId)?'/'.$this->publisherId:'';?>/edit"><?php echo $this->translate('my.company')?></a>
        </div>
        <div>
            <a href="shoplist"><?php echo $this->translate('my.shops')?></a>
        </div>
        <div>
            <a href="objects"><?php echo $this->translate('my.objects')?></a>
        </div>
		<div>
            <a href="user/<?php echo $this->userId; ?>/edit" class="navDivlastChildA"><?php echo $this->translate('user.edit')?></a>
        </div>
    <?php } ?>
    <?php 
        if($this->isUser){
        ?>
        <div>
            <a href="lovelist" class="navDivlastChildA"><?php echo $this->translate('lovelist')?></a>
        </div>
    <?php } ?>
    <div id="loginInfo">  
        <?php echo $this->action("login", "auth"); ?>
    </div>
</div>