<script>
	selected = '';
	$(function(){
		$('.menu').click(function(){
			$('.forFInd').hide(500);
		});
		$('.objectsTypes').click(function(){
			if(selected != 'objectsTypes'){
				selected = 'objectsTypes';
				$('.forFInd').hide(500);
				$('.objectsTypesLink').show(500);
			}
		});
	});

</script>
<?php 
	mb_internal_encoding("UTF-8");
	echo header( "Content-Type: text/html;charset=UTF-8", true );
?>	
    <div class="nav">
    <?php 
        if(!$this->isPublisher && !$this->isAdmin){
        ?>
		<div>
			<a href="objecttype"><?php echo $this->translate('objecttype')?></a>
		</div>
		<div>
			<a href="brand"><?php echo $this->translate('brand')?></a>
		</div>
		<div>
			<a href="shoplist"><?php echo $this->translate('shoplist')?></a>
		</div>	
        <div>
            <a href="lovelist" class="navDivlastChildA"><?php echo $this->translate('try.it')?></a>
        </div>
		<?php if($this->isUser){ ?>
			<div>
				<a href="user/<?php echo $this->userId; ?>/edit" class="navDivlastChildA"><?php echo $this->translate('user.edit')?></a>
			</div>
		<?php } ?>
    <?php } else if(!$this->isAdmin){ 
        ?>
        <div>
            <a href="publisher<?php echo ($this->publisherId)?'/'.$this->publisherId:'';?>/edit"><?php echo $this->translate('my.company')?></a>
        </div>
        <div>
            <a href="shoplist"><?php echo $this->translate('my.shops')?></a>
        </div>
        <div>
            <a href="objects"><?php echo $this->translate('my.objects')?></a>
        </div>
		<div>
            <a href="discounts"><?php echo $this->translate('discount')?></a>
        </div>
		<div>
            <a href="user/<?php echo $this->userId; ?>/edit" class="navDivlastChildA"><?php echo $this->translate('user.edit')?></a>
        </div>

    <?php }else{  ?>
        <div>
            <a href="superadmin"  class="navDivlastChildA"><?php echo $this->translate('home')?></a>
        </div>
        <div>
            <a href="material"><?php echo $this->translate('materials')?></a>
        </div>
        <div>
            <a href="objecttype"><?php echo $this->translate('objectType')?></a>
        </div>
		<div>
            <a href="brand"><?php echo $this->translate('brands')?></a>
        </div>
		<div>
            <a href="color"  class="navDivlastChildA"><?php echo $this->translate('color')?></a>
        </div>
    <?php
        }
    ?>
    <div id="loginInfo">  
        <?php if(!$this->isPublisher && (!$this->isUser) && (!$this->isAdmin)){
        ?>
            <div>
                <a href="user/add" class="button w50 fr mt10 mr10" ><?php echo $this->translate('sign.up')?></a>
                <a href="auth/login" class="button w50 fr mt10 mr10"><?php echo $this->translate('sign.in')?></a>
            </div>
        <?php 
            }else{
        ?>
            <form action="auth/logout" method="POST" id="loginForm" name="loginForm">
                <div><a class="button fr mt5 ml20 mr20" onclick = 'Filter.submit("loginForm","loginInfo");' ><?php echo $this->translate('log.out') ?></a></div>
                <img class="fr ml20 mt5 mr20" style="height:25px;width:25px;" src="<?php echo $this->path; ?>">
                <div class="fr textW pt8 ml20"><?php echo $this->translate('hi').'  '.$this->name; ?></div>
            </form>
        <?php 
            }
        ?>
    </div>
	
</div>
