<script>
	$(function(){
		Menu.acitvate('objects');
		initialize();
	});
		my_position=null;

		function initialize() {
			positions = eval("("+<?php echo (($this->shopList && $this->shopList->getMapControl()) ? $this->htmlEscape($this->shopList->getMapControl()):'"{lat:15,long:15}"')?>+")");
			position = new google.maps.LatLng(positions.lat,positions.long);
		    var mapOptions = {
			    zoom: 18,
				center: position,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			var map = new google.maps.Map(document.getElementById('divForMap'),
				mapOptions);
			if(position){
				/*if(navigator.geolocation) {
					navigator.geolocation.getCurrentPosition(function(position) {
					var pos = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
							map.setCenter(pos);
							marker = new google.maps.Marker({
								position: pos,
								map: map,
								center: pos
							});
					}, function() {
						
					});
				} else {
					
				}*/
				marker = new google.maps.Marker({
					position: position,
					map: map,
					center: position
				});
				
			}
		}
</script>

<div class="overviewDiv">
	<div class="overviewImageDiv">
		<div><?php  echo $this->item->getName(); ?></div>
		
		
		<div id="ok_shareWidget" class="fl">		</div>	
		<div id="fb-root">
			<br>
			<img src="<?php  echo $this->item->getPath(); ?>">
			<br>
		</div>
		
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1&appId=1408093126081266";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
		
		<div class="fb-like" data-href="http://localhost/shoplist" data-width="100" data-layout="button_count" data-show-faces="true" data-send="false"></div>
		
		<script>
		!function (d, id, did, st) {
		  var js = d.createElement("script");
		  js.src = "http://connect.ok.ru/connect.js";
		  js.onload = js.onreadystatechange = function () {
		  if (!this.readyState || this.readyState == "loaded" || this.readyState == "complete") {
			if (!this.executed) {
			  this.executed = true;
			  setTimeout(function () {
				OK.CONNECT.insertShareWidget(id,did,st);
			  }, 0);
			}
		  }};
		  d.documentElement.appendChild(js);
		}(document,"ok_shareWidget","http://cosmopoliten.p.ht/shoplist/"+<?php  echo $this->item->getId(); ?>+"/overview","{width:70,height:50,st:'straight',sz:12,ck:1,vt:'1'}");
	</script>

	</div>
	<div  class="overviewInfoDiv">
	
		<table>
			<tr>
				<td>
					<label for="phone"><?php echo $this->translate('shop.phone'); ?></label>
					<div>:</div>
				</td>
				<td>
					<span name="phone"><?php  echo $this->shopList->getPhone(); ?></span>
				</td>
			</tr>
			<tr>
				<td>
					<label for="address"><?php echo $this->translate('shop.address'); ?></label>
					<div>:</div>
				</td>
				<td>
					<span name="address"><?php  echo $this->shopList->getAddress(); ?></span>
				</td>
			</tr>
			<tr>
				<td>
					<label for="name"><?php echo $this->translate('shop.name'); ?></label>
					<div>:</div>
				</td>
				<td>
					<span name="name"> 
						<a href="shoplist/<?php  echo $this->shopList->getId(); ?>/overview" class="link"> 
							<?php  echo $this->shopList->getName(); ?> 
						</a>
					</span>
				</td>
			</tr>
			<tr>
				<td>
					<label for="webPage"><?php echo $this->translate('shop.website'); ?></label>
					<div>:</div>
				</td>
				<td>
					<span name="webPage">
						<a href="http:\\www.<?php  echo $this->shopList->getSite(); ?>" class="link"> 
							<?php  echo $this->shopList->getSite(); ?>
						</a>
					</span>
				</td>
			</tr>
			<tr>
				<td>
					<label for="cost"><?php echo $this->translate('object.cost'); ?></label>
					<div>:</div>
				</td>
				<td>
					<span name="cost"><?php  echo $this->item->getCost(); ?></span> <span><?php  echo $this->getValuta($this->item->getValuta()); ?></span>
				</td>
			</tr>
		</table>
	</div>
	<div style="" class="divForDescription" >
		<div id="divForMap">map</div>
		<?php  echo $this->item->getDescription(); ?>
	</div>
	<?php 
		if($this->objectsInGroup){
			var_dump($this->objectsInGroup);
		}
	?>
</div>