<script>
	$(function(){
		
	});
</script>
<form action="auth/login" method="POST" id="loginForm" name="loginForm">
    <div id="loginInfo">  
    <?php
        if($this->name){
            echo '<span class="fl">'.$this->translate('hi').'  '.$this->name.'</span>'; ?><img class="fl mr5 mt5 ml5" style="height:25px;width:25px;" src="<?php echo $this->img; ?>">
			<input  class="fl ml5 mt5" type="button" onclick = 'Form.changeAction("loginForm","auth/logout");Filter.submit("loginForm","loginInfo");' class="loginButton" value="<?php echo $this->translate('log.out') ?>">
            
     <?php   }else {
     ?>		
			<div>
				<label class="mt5 loginError">
					<?php 
					if($this->loginfailed) { 
						echo $this->translate('auth.failed'); 
					} 
					?>	
				</label>
			</div>	
			<div  class=" mt5">
				<input type="text" id="username" class="w120" name="email" placeholder="Username">
			</div>
			<div  class=" mt5">    
				<input type="password" id="password" name="password" placeholder="Password" class="w120">
			</div>
			<div class="fl">	
				<input  class="mr5 w50 mt5" type="button" onclick = 'Form.changeAction("loginForm","auth/login");Filter.submit("loginForm","loginInfo");'class="loginButton" value="<?php echo $this->translate('log.in') ?>">
			</div>
			<div class="fl">
				<a href="user/edit" class="ml5 mt5 link registr">Registration</a>
			</div>
			
    <?php
        }
    ?>
    </div>
 </form>
