 <?php   if(!$this->name){
?>	
<div class="w350 center editBorders">
    <form action="auth/login" method="POST" id="loginForm" name="loginForm">
        <div id="tempForReload"></div>
        <div class="fixed_head">
            <span class="tableTitle"><?php echo $this->translate('login'); ?></span>        
            <table class="editTable">                    
                <tbody>                    
                    <tr>
                        <td class="middle left w180"><label for="email"><?php echo $this->translate('email')?> *</label></td>
                        <td class="middle left">
                            <input type="text" id="username" name="email" class="textField mt5" placeholder="<?php echo $this->translate('email')?>">
                        </td>                    
                    </tr>    
                    <tr>
                        <td class="middle left w150"><label for="firstName"><?php echo $this->translate('password')?></label></td>
                        <td class="middle left">
                            <input type="password" id="password" class="textField mt5" name="password" placeholder="<?php echo $this->translate('password')?>">
                        </td>
                    </tr>
                    <tr>
                       <td class="middle" colspan="2">
                           <a class="button mt5 w50" style="margin-left:auto;margin-right:auto; margin-bottom:5px;" onclick = 'Filter.submit("loginForm","loginInfo");'><?php echo $this->translate('log.in') ?></a>
                       </td>
                    </tr>
            </table>
        </div> 
    </form>
</div>
<?php
}
?>

