<div>
    <script>
        $(function(){
            LoveListObject.init();
        });
    </script>
	<?php 
		foreach($this->items as $item){
	?>
		
        
        
        <div data-id="object_<?php echo $item->getId();?>" class="objectContentDiv fl">
            <div class="objectHeader">
                <div>
                    <?php echo ($item->getName())?$item->getName():'no description';?>
                </div>
            </div>
            <div class="objectDiv">
                <img src="<?php echo $item->getPath(); ?>">
            </div>
            <div class="favourDiv">
                <a data-img="oneStar.png" data-evaluation="1"></a>
                <a data-img="twoStars.png" data-evaluation="2"></a>
                <a data-img="threeStars.png" data-evaluation="3"></a>
                <a data-img="fourStars.png" data-evaluation="4"></a>
                <a data-img="fiveStars.png" data-evaluation="5"></a>
            </div>    
            <div class="actionDiv">
                <div>
                </div>
                <a href="objects/<?php echo $item->getId() ?>/publisher/index" class="link fl textw pt8"><?php echo $this->translate('go.to.company.products');?></a>
                <a href="publisher/<?php echo $item->getId();?>/overview" class="link fl overview" ></a>
            </div>
        </div>
	<?php
		}
	?>
</div>