<?php 
    $this->setPageTitle('material'); 
    $formatting = $this->getHelper('DataFormatting');
?>
<script>
$(function(){
    Grid.init('club/list');
});

</script>
<div id="deleteFormDiv">

</div>
<?php if($this->isAdmin){ ?>
    <a class="button fl mt5 ml20 mr20" href="material/add" ><?php echo $this->translate('add') ?></a><br><br><br><br>
<?php } ?>
<?php echo $this->action('list', 'material');?></td>
    


