<div>
	<?php 
		foreach($this->items as $item){
	?>
        <a href="objects/<?php echo $item->getId() ?>/material/index">
            <div data-id="object_<?php echo $item->getId();?>" class="objectContentDiv fl">
                <div class="objectHeader">
                    <div>
                        <?php echo $this->translate(($item->getName())?$item->getName():'no description');?>
                    </div>
                </div>
                <div class="objectDiv">
                    
                </div>   
                <div class="actionDiv">
                    
                </div>
            </div>
        </a>
	<?php
		}
	?>
</div>