<?php 
    $this->setPageTitle('brands'); 
    $formatting = $this->getHelper('DataFormatting');
?>
<script>
$(function(){
    Grid.init('club/list');
});

</script>
<script>
$(function(){
	Menu.acitvate('brand');
});

</script>
<div id="deleteFormDiv">

</div>
<?php if($this->isAdmin){ ?>
    <a class="button fl mt5 ml20 mr20" href="brand/add" ><?php echo $this->translate('add') ?></a>
<?php } ?>
<?php echo $this->action('list', 'brand');?></td>
    


