<?php if($this->items || $this->isAuth){ ?>
    <div id="ImageDiv" class="fl">
        <span><img src="<?php echo $this->img ?>" style="z-index: 1;width:400px" id="templateMan"/></span>
    </div>
    <div><a href="user/<?php echo $this->id ?>/edit" class="link">edit</a></div>
    <div class="fl w800">
        <table class="mt20">
            <tbody>
                <tr class="head">
                    <td>
						<script>
							LoveListDeleteObject = {
								objectsCount : 0,
								addLovleList : function(id){
									$('#'+id).attr('class','selectedLoveList');
									//$('#'+id).attr('onclick','LoveListObject.deleteFromSaveList("'+id+'")');
									id = id.replace('remove_','');
									str = '<input type="hidden" id="template_'+id+'" name="ids[]" value="'+id+'"/>';
									$('#addForm').append(str);
									LoveListDeleteObject.objectsCount++;
								},
								
								deleteFromSaveList: function(id){
									$('#'+id).attr('class','unSelectedLoveList');
									id = id.replace('remove_','');
									$('#template_'+id).remove();
									LoveListDeleteObject.objectsCount--;
								},
								
								detectOption : function(id){
									if($('#'+id).attr('class')=='selectedLoveList'){
										LoveListDeleteObject.deleteFromSaveList(id);
									}else{
										LoveListDeleteObject.addLovleList(id);
									}
								}
							}
                            
						</script>
						<script>
						$(function(){
							Cosmo_object.init();
                            LoveListObject.init();
                            $('#manHeight').attr('value',parseInt($('#templateMan').height()));
                            $('#manWidth').attr('value',parseInt($('#templateMan').width()));
						});
						</script>
						<div>
							<form id="addForm" name="addForm" action="lovelist/delete">
								
							</form>
							<form action="image/list" name="imgGenerate" method="POST" id="imgGenerate">
                                <input type="hidden" name="width" id="manWidth" value="">
                                <input type="hidden" name="height" id="manHeight" value="">
								<input type="button" onclick="Filter.submit('imgGenerate')" value="saveImg" class="">
							</form>
							<input type="button" onclick="Form.submit('addForm')" value="submit">
						   
						</div>
						<div id="objectList" style="width:100%;">
							<?php
								foreach($this->items as $item){
							?>
                                	
								<div data-id="object_<?php echo $item->getId();?>" class="objectContentDiv fl">
                                    <div class="objectHeader">
                                        <div>
                                            <?php echo ($item->getName())?$item->getName():'no description';?>
                                        </div>
                                    </div>
                                    <div class="objectDiv">
                                        <img src="<?php echo $item->getPath();?>">
                                    </div>
                                    <div class="favourDiv">
                                        <a data-img="oneStar.png" data-evaluation="1"></a>
                                        <a data-img="twoStars.png" data-evaluation="2"></a>
                                        <a data-img="threeStars.png" data-evaluation="3"></a>
                                        <a data-img="fourStars.png" data-evaluation="4"></a>
                                        <a data-img="fiveStars.png" data-evaluation="5"></a>
                                    </div>    
                                    <div class="actionDiv">
                                        <div>
                                            <?php echo ($item->getCost())?$item->getCost():'0';?> <?php echo $this->getValuta($item->getValuta()); ?>
                                        </div>
                                        <a class="unSelectedLoveList" id="add_<?php echo $item->getId();?>" onclick="LoveListObject.detectOption('add_<?php echo $item->getId();?>')"></a>
                                        <a href="" class="link fl overview" ></a>
                                    </div>
                                </div>
							<?php
								}
							?>
						</div>
                    </td>
                </tr>
                <tr class='panel'>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
<?php }else{ ?>
    please Login or registrate 
<?php } ?>