<div id="ImageDiv" class="fl">
	<span><img src="man/manikenGirl.jpg" style="z-index: 1;width:300px" id="templateMan"/></span>
</div>
<div class="fl">
    <table class="mt20">
    	<tbody>
    		<tr class="head">
                <td>
                </td>
            </tr>
    		<tr class='panel'>
    			<td><?php echo $this->action('list', 'lovelist');?></td>
    		</tr>
    	</tbody>
    </table>
</div>