<div class="w350 center editBorders">
<?php
    $this->setPageTitle('user.management');
    $formatting = $this->getHelper('DataFormatting');
?>
<script type="text/javascript">
    $(function(){
    	Menu.acitvate('user');        
    });
</script>
<?php
    if($this->isPublisher){
?>
    <form id="ajaxForm" action="shoplist/save" method="post" onsubmit="Form.submit('ajaxForm'); return false;">
        <input type="hidden" name="id" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getId()):'')?>" />
        <input type="hidden" name="publisherId" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getPublisherId()):'')?>" />
        <div class="fixed_head">
            <span class="tableTitle"><?php echo $this->translate('publisher'). ' // ' . ($this->item ? $this->translate('edit'): $this->translate('add')); ?></span>        
            <table class="editTable">                    
                <tbody>                    
                    <tr>
                        <td class="middle left w180"><label for="name"><?php echo $this->translate('name')?> *</label></td>
                        <td class="middle left"><input type="text" name="name" id="name" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getName()):'')?>"/></td>                    
                    </tr>    
                    <tr>
                        <td class="middle left w150"><label for="address"><?php echo $this->translate('address')?></label></td>
                        <td class="middle left"><input type="text" name="address" id="address" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getAddress()):'')?>"/></td>
                    </tr>
                    <tr>
                        <td class="middle left"><label for="phone"><?php echo $this->translate('phone')?></label></td>
                        <td class="middle left"><input type="text" name="phone" id="phone" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getPhone()):'')?>"/></td>
                    </tr>
                    <tr>
                        <td class="middle left"><label for="description"><?php echo $this->translate('description')?></label></td>
                        <td class="middle left"><input type="text" name="description" id="description" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getDescription()):'')?>"/></td>
                    </tr>
                    <tr>
                        <td class="middle left"><label for="path"><?php echo $this->translate('image')?> *</label></td>
                        <td class="middle left">
                            <input type="file" name="path" id="path" value="<?php echo ($this->img ? $this->htmlEscape($this->img->getPath()):'')?>" class="mt10 ml8"/>
                        </td>
                    </tr>	
                    <?php
                        if($this->item){
                    ?>
                        <tr>
                            <td class="middle left"><label for="description"><?php echo $this->translate('population')?></label></td>
                            <td class="middle left">
								<div class="mt5 ml8"><?php echo ($this->item ? $this->htmlEscape($this->item->getPopulation()):'')?></div>	
							</td>
                        </tr>
                    <?php
                        }
                    ?>
					<tr>
                        <td class="middle left"><label for="site"><?php echo $this->translate('site')?></label></td>
                        <td class="middle left"><input type="text" name="site" id="site" value="<?php echo ($this->item ? $this->htmlEscape($this->item->getSite()):'')?>"/></td>
                    </tr> 
                    <tr>
                        <td class="middle left"></td>
                        <td class="middle left">
							<a class="button mt5 w50" onclick="Form.submit('ajaxForm')" ><?php echo $this->translate('save')?></a>
						</td>
                    </tr>                     
                </tbody>
                <tfoot><tr><td class="h p5_0"></td></tr></tfoot>
            </table>
        </div> 
    </form>
    <?php }else{ ?>
        <div>
            <?php echo $this->translate('this.action.only.for.publishers');?>
        </div>
    <?php } ?>
</div>