<?php 
    $this->setPageTitle('shops'); 
    $formatting = $this->getHelper('DataFormatting');
?>

<script>
$(function(){
	Menu.acitvate('shoplist');
});

</script>
<div class="table_wrapper ml20 mt20">
    <?php if($this->isPublisher){ ?>
		<div>
			<a href="shoplist/add" class="button w100 fl">
				<?php echo $this->translate('add.shop'); ?>
			</a>
			<a href="shopsgroup/add" class="button w100 fl">
				<?php echo $this->translate('add.group'); ?>
			</a>
		</div>
		<br>
    <?php } else{ ?>    
	<form action="shoplist/list" name="ajaxForm" id="ajaxForm">
		<div class="mr5 fl mt-5">
			<select name="publisherId" id="publisherId">
				<option value="">--Select--</option>
				<?php
					foreach($this->items as $item){
				?>
					<option value="<?php echo $item->getId() ?>"><?php echo $this->translate($item->getName()); ?></option>
				<?php
					}
				?>
			</select>
		</div>
		<div class="fl">
            <a class="button ml10 w100" onclick="Filter.submit('ajaxForm');return false;" ><?php echo $this->translate('filter'); ?> </a>
		</div>
	</form>
    <br>
    <?php } ?>
    <table class="mt20">
    	<tbody>
    		<tr class='panel'>
    			<td><?php echo $this->action('list', 'shoplist');?></td>
    		</tr>
    	</tbody>
    </table>
</div>


