
<div>
	<?php 
		foreach($this->items as $item){
	?>
		<div class="mr5 mt5 fl">
			<a class="link" href="publisher/<?php echo $item->getId() ?>/overview">
				<div class="name">
					<?php echo $item->getName(); ?>
				</div>
				<div class="name">
					<img src="<?php echo $item->getName(); ?>" class="w100"/>
				</div>
			</a>
            <a class="link" href="objects/<?php echo $item->getId() ?>/shopList/index">go to shop products</a>
            <br>
            <?php
                if($this->isPublisher){
            ?>
                <a class="link" href="shoplist/<?php echo $item->getId() ?>/edit">edit shop</a>
            <?php 
                }
            ?>
		</div>
	<?php
		}
	?>
</div>
